name: QW Scraper Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          pip install requests pyyaml playwright playwright-stealth
          playwright install chromium

      - name: Run QW Script
        run: python qw_sync.py

      - name: Save and Push qw files
        run: |
          git config --global user.name "Lucra-Bot"
          git config --global user.email "bot@lucra.internal"
          
          # This 'rebase' fixes the error when you edit files on the web manually
          git pull origin main --rebase
          
          if ls qw_* 1> /dev/null 2>&1; then
            git add qw_*
            git commit -m "Update Lucra results: $(date)"
            git push origin main
          else
            echo "No files generated to commit."
          fi
